### ISSUE TITLE
How to repaint the graph?

### ISSUE THREAD

**Issue by scrobbleme** [fperucic/treant-js#25]
Hi,

is it possible to repaint the graph?

I've have a switch for hiding/showing elements, which resizes the nodes. But the lines between are recalculated.

**Comment by scrobbleme** [comment]
My workaround:

Pseudocode

    destroy treant
    change node structure (through CSS)
    create treant

Not nice, but working.

**Comment by PepaBosnis** [comment]
Hi,
repaint graph is possible, but:

- if I used the method to "destroy" was removed a visual presentation only, but the data remained in the object. This is useful if you change only the display properties (eg. Orientation). In any event it was also necessary to remove the entire element into which the graph inserted, this action is necessary for reset the location.

- but I needed change the structure of the data and draw the graph again. This, however was not possible, until were not erased data from the array TreeStore.strore, so I was added the method "remove" for to remove this data from this array. It was also necessary do reset the counter IDs in JSONconfig, "destroy" method does not reset this ID so each redraw changes the value iD, and I could not used new data

**Comment by dlgoodchild** [comment]
This is now possible on the latest version by calling the `.reload()` method directly on the Tree instance.

**Comment by Cristinutaa** [comment]
var chart = new Treant(chart_config);
chart.reload();
gives me an error that the function doesn't exist

**Comment by mmattia993** [comment]
Hi Cristinutaa,

try this:

chart.tree.reload();

It should work :)

**Comment by Leepoff** [comment]
It seems that when I change the node data (innerNodeHTML in this case) it reads the init JSON object to rebuild the tree and any changes I've made to the nodes get reset. Is there a specific way to alter the node HTML so that the changes are saved when I redraw the tree?

In this case similar to the OP I alter an element in the node so that it shrinks in size, which causes the node to become offset from the connector lines and other nodes around it.
