### ISSUE TITLE
Nodes are not shown

### ISSUE THREAD

**Issue by chaddwick25** [fperucic/treant-js#64]
Hi,

I am having an issue when loading  alot of nodes on screen.  I will not get any errors but some of the  nodes  will not show up on screen. I am passing the nodes in a php array.  I am wondering if it is a memory issue because I am loading of 75, 000 nodes. 

Thanks

**Comment by dlgoodchild** [comment]
I would guess that you're hitting some kind of browser/memory limitation there. That's an incredible amount of data, do you really need to load 75k tree nodes? As an end user, there's no possible way anyone could traverse that manually and actually make much sense of it.

I'm going to close this issue, because I doubt that's a common usage scenario as most people would filter the data or work with snapshots of limited depth; and I can't see use generating that amount of data to debug this.

Thanks.

**Comment by chaddwick25** [comment]
Thank you for responding and I think you are right. I have modified my code to do a partial load of the array through ajax.
