### ISSUE TITLE
Child Node connect to other parent node (Image is attached)

### ISSUE THREAD

**Issue by sarvweb** [fperucic/treant-js#68]
Hi 
I have an attached image to explain you what we need in the js. **According to image, one parent node should be connect to other parent child node, also it can be connect to one parent node to other parent node.**
Hope you understand my issue and my requirement. 
Plz try to give the solution for this as soon as possible. If you have any query plz ask.

![connector-required](https://cloud.githubusercontent.com/assets/15045234/26197868/7e9e3444-3be1-11e7-9aeb-54929d720296.png)

Looking forward to your reply.

Thanks and Regards
Peeyush

**Comment by dlgoodchild** [comment]
Hi, this has been asked a number of times before and is currently not supported in the library. There are no guarantees that it ever will, unless someone out there wishes to make the necessary changes and make a pull request. This feature can become quite complicated, because as soon as the additional parent is actually in a more distant column, the path and the adjustments to the nodes to create that path gets increasingly more complicated.

I personally do not have the available time to implement such functionality, so it will likely need to come from someone out in the community.

Good luck.

**Comment by sarvweb** [comment]
Thanks for your prompt reply.
Can you suggest the js framework or plugin that fulfill my functionality.

Thanks in advance.

Thanks & Regards,
Peeyush Gupta


*Design Head+919928362554*

*Sarv Webs Pvt Ltd.*
*Corporate Office:* 503-514, 5th Floor, Sunny Paradise, Tonk road, Jaipur
*Dir:*- 0141- 3367026, 0141-3367000
Email: p.gupta@sarv.com Website: www.sarv.com, www.sarvmail.com,
www.tld6.com

**Comment by dlgoodchild** [comment]
Sorry, I don't know of one that does this.
